spring:
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./db/shareit
    username: shareit
    password: shareit
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
logging:
  level:
    org:
      springframework:
        transaction:
          nodeValue: INFO
          interceptor: TRACE
        orm:
          jpa:
            JpaTransactionManager: DEBUG
            nodeValue: INFO